#!/bin/sh
# simple script to run matlab script
if [ $# -eq 0 ]
  then
    echo "please pass m script"
fi

matlab -nodisplay -nosplash -nodesktop -r "run('$1');"

# see here:https://stackoverflow.com/questions/38723138/matlab-execute-script-from-linux-command-line
